"""Initial migration

Revision ID: ce05c9aacb8a
Revises: 
Create Date: 2022-02-03 10:47:27.948611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce05c9aacb8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('viewer_hour', sa.Integer(), nullable=True),
    sa.Column('hours_streamed', sa.Integer(), nullable=True),
    sa.Column('acv_num', sa.Integer(), nullable=True),
    sa.Column('creators', sa.Integer(), nullable=True),
    sa.Column('streams_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
